"""Import SQL schema to Supabase database using REST API."""

print("=" * 80)
print("IMPORTANT: SQL schema must be imported manually to Supabase")
print("=" * 80)
print()
print("1. Go to: https://supabase.com/dashboard/project/wmyldpegqudnzoxpudmv/editor")
print("2. Click 'SQL Editor' in left sidebar")
print("3. Click 'New Query'")
print("4. Copy and paste the contents of:")
print("   packages/core/migrations/001_initial_schema.sql")
print("5. Click 'Run' to execute the schema")
print()
print("=" * 80)
print("Schema file location: packages/core/migrations/001_initial_schema.sql")
print("=" * 80)
print()
print("The schema creates these tables:")
print("  - organizations")
print("  - users")
print("  - user_sessions")
print("  - agents")
print("  - conversations")
print("  - messages")
print("  - tool_executions")
print("  - vault_entries")
print("  - vault_evidence")
print("  - audit_events")
print("  - cost_tracking")
print()
print("Press Enter when schema import is complete...")
input()
print("✅ Continuing with deployment...")
